import type { Metadata } from "next";
import { Geist, Geist_Mono, Cinzel, EB_Garamond, Lora, Noticia_Text} from "next/font/google";
import "./globals.css";
import Banner from "@/components/ui/Banner"
import { AuthProvider } from "@/components/ui/context/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
});
const garamond = EB_Garamond({
  variable: "--font-garamond",
  subsets: ["latin"],
});
const lora = Lora({
  variable: "--font-lora-serif",
  subsets: ["latin"],
})
const noticia = Noticia_Text({
  variable:"--font-noticia-serif",
  subsets: ["latin"], 
  weight: ["400", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1, maximum-scale=5",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //{<Banner links={[{label:"Home", href:"/"},{label:"References",href:"/refrences"},{label:"Discuss",href:"/discussion"},{label:"Users",href:"/users"},]}/> */}
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${cinzel.variable} ${garamond.variable} ${lora.variable} ${noticia.variable} antialiased`}>
        <AuthProvider >
                {children}
        </AuthProvider>
      </body>
    </html>
  );
}
